"""add onet soc code to career goals

Revision ID: 0d0919441a3b
Revises: 6185abdd131e
Create Date: 2026-10-02 17:48:57.432974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0919441a3b'
down_revision: Union[str, Sequence[str], None] = '6185abdd131e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_goals', sa.Column('onet_soc_code', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_career_goals_onet_soc_code'), 'career_goals', ['onet_soc_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_goals_onet_soc_code'), table_name='career_goals')
    op.drop_column('career_goals', 'onet_soc_code')
    # ### end Alembic commands ###
