"""create career twin tables

Revision ID: 14bd65acd0a3
Revises: 220399a37fce
Create Date: 2026-10-01 10:58:47.422840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14bd65acd0a3'
down_revision: Union[str, Sequence[str], None] = '220399a37fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_twins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_career_twin_user')
    )
    op.create_index(op.f('ix_career_twins_user_id'), 'career_twins', ['user_id'], unique=False)
    op.create_table('career_twin_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_twin_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_twin_id'], ['career_twins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_twin_events_career_twin_id'), 'career_twin_events', ['career_twin_id'], unique=False)
    op.create_index(op.f('ix_career_twin_events_event_type'), 'career_twin_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_career_twin_events_occurred_at'), 'career_twin_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_career_twin_events_source_type'), 'career_twin_events', ['source_type'], unique=False)
    op.create_table('career_twin_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_twin_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('schema_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_twin_id'], ['career_twins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_twin_id', 'version', name='uq_career_twin_snapshot_version')
    )
    op.create_index(op.f('ix_career_twin_snapshots_career_twin_id'), 'career_twin_snapshots', ['career_twin_id'], unique=False)
    op.create_index(op.f('ix_career_twin_snapshots_created_at'), 'career_twin_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_career_twin_snapshots_trigger_type'), 'career_twin_snapshots', ['trigger_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_twin_snapshots_trigger_type'), table_name='career_twin_snapshots')
    op.drop_index(op.f('ix_career_twin_snapshots_created_at'), table_name='career_twin_snapshots')
    op.drop_index(op.f('ix_career_twin_snapshots_career_twin_id'), table_name='career_twin_snapshots')
    op.drop_table('career_twin_snapshots')
    op.drop_index(op.f('ix_career_twin_events_source_type'), table_name='career_twin_events')
    op.drop_index(op.f('ix_career_twin_events_occurred_at'), table_name='career_twin_events')
    op.drop_index(op.f('ix_career_twin_events_event_type'), table_name='career_twin_events')
    op.drop_index(op.f('ix_career_twin_events_career_twin_id'), table_name='career_twin_events')
    op.drop_table('career_twin_events')
    op.drop_index(op.f('ix_career_twins_user_id'), table_name='career_twins')
    op.drop_table('career_twins')
    # ### end Alembic commands ###
