"""create skill competency mappings

Revision ID: 6185abdd131e
Revises: c9f62eae4df4
Create Date: 2026-10-02 15:39:06.672178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6185abdd131e'
down_revision: Union[str, Sequence[str], None] = 'c9f62eae4df4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_competency_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('onet_element_id', sa.String(length=50), nullable=False),
    sa.Column('onet_element_name', sa.String(length=200), nullable=False),
    sa.Column('mapping_type', sa.String(length=50), nullable=False),
    sa.Column('mapping_version', sa.String(length=50), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'onet_element_id', name='uq_skill_competency_mapping')
    )
    op.create_index(op.f('ix_skill_competency_mappings_is_active'), 'skill_competency_mappings', ['is_active'], unique=False)
    op.create_index(op.f('ix_skill_competency_mappings_onet_element_id'), 'skill_competency_mappings', ['onet_element_id'], unique=False)
    op.create_index(op.f('ix_skill_competency_mappings_onet_element_name'), 'skill_competency_mappings', ['onet_element_name'], unique=False)
    op.create_index(op.f('ix_skill_competency_mappings_skill_id'), 'skill_competency_mappings', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_competency_mappings_skill_id'), table_name='skill_competency_mappings')
    op.drop_index(op.f('ix_skill_competency_mappings_onet_element_name'), table_name='skill_competency_mappings')
    op.drop_index(op.f('ix_skill_competency_mappings_onet_element_id'), table_name='skill_competency_mappings')
    op.drop_index(op.f('ix_skill_competency_mappings_is_active'), table_name='skill_competency_mappings')
    op.drop_table('skill_competency_mappings')
    # ### end Alembic commands ###
