"""create career goals table

Revision ID: 749a0b93af08
Revises: 3eab16ab7cea
Create Date: 2026-09-25 19:52:58.185156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '749a0b93af08'
down_revision: Union[str, Sequence[str], None] = '3eab16ab7cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('target_industry', sa.String(length=200), nullable=True),
    sa.Column('target_location', sa.String(length=200), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('target_timeline_months', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_goals_user_id'), 'career_goals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_goals_user_id'), table_name='career_goals')
    op.drop_table('career_goals')
    # ### end Alembic commands ###
