"""create riasec assessment tables

Revision ID: 7b1d39f45efe
Revises: c20b9d2fb9d1
Create Date: 2026-09-28 20:35:02.155964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b1d39f45efe'
down_revision: Union[str, Sequence[str], None] = 'c20b9d2fb9d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('riasec_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('assessment_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riasec_assessments_status'), 'riasec_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_riasec_assessments_user_id'), 'riasec_assessments', ['user_id'], unique=False)
    op.create_table('riasec_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.String(length=30), nullable=False),
    sa.Column('dimension', sa.String(length=1), nullable=False),
    sa.Column('response_value', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['riasec_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_riasec_answer_assessment_question')
    )
    op.create_index(op.f('ix_riasec_answers_assessment_id'), 'riasec_answers', ['assessment_id'], unique=False)
    op.create_table('riasec_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('realistic', sa.Float(), nullable=False),
    sa.Column('investigative', sa.Float(), nullable=False),
    sa.Column('artistic', sa.Float(), nullable=False),
    sa.Column('social', sa.Float(), nullable=False),
    sa.Column('enterprising', sa.Float(), nullable=False),
    sa.Column('conventional', sa.Float(), nullable=False),
    sa.Column('dominant_code', sa.String(length=6), nullable=False),
    sa.Column('scoring_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['riasec_assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', name='uq_riasec_profile_assessment')
    )
    op.create_index(op.f('ix_riasec_profiles_assessment_id'), 'riasec_profiles', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_riasec_profiles_user_id'), 'riasec_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_riasec_profiles_user_id'), table_name='riasec_profiles')
    op.drop_index(op.f('ix_riasec_profiles_assessment_id'), table_name='riasec_profiles')
    op.drop_table('riasec_profiles')
    op.drop_index(op.f('ix_riasec_answers_assessment_id'), table_name='riasec_answers')
    op.drop_table('riasec_answers')
    op.drop_index(op.f('ix_riasec_assessments_user_id'), table_name='riasec_assessments')
    op.drop_index(op.f('ix_riasec_assessments_status'), table_name='riasec_assessments')
    op.drop_table('riasec_assessments')
    # ### end Alembic commands ###
