"""create career knowledge tables

Revision ID: c20b9d2fb9d1
Revises: 749a0b93af08
Create Date: 2026-09-28 19:26:45.899884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20b9d2fb9d1'
down_revision: Union[str, Sequence[str], None] = '749a0b93af08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('careers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('onet_soc_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('job_zone', sa.Integer(), nullable=True),
    sa.Column('onet_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_onet_soc_code'), 'careers', ['onet_soc_code'], unique=True)
    op.create_index(op.f('ix_careers_title'), 'careers', ['title'], unique=False)
    op.create_table('career_riasec_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('realistic', sa.Float(), nullable=True),
    sa.Column('investigative', sa.Float(), nullable=True),
    sa.Column('artistic', sa.Float(), nullable=True),
    sa.Column('social', sa.Float(), nullable=True),
    sa.Column('enterprising', sa.Float(), nullable=True),
    sa.Column('conventional', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('onet_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', name='uq_career_riasec_profile_career_id')
    )
    op.create_index(op.f('ix_career_riasec_profiles_career_id'), 'career_riasec_profiles', ['career_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_riasec_profiles_career_id'), table_name='career_riasec_profiles')
    op.drop_table('career_riasec_profiles')
    op.drop_index(op.f('ix_careers_title'), table_name='careers')
    op.drop_index(op.f('ix_careers_onet_soc_code'), table_name='careers')
    op.drop_table('careers')
    # ### end Alembic commands ###
