"""add primary flag to career goals

Revision ID: c326b0c451ac
Revises: 0d0919441a3b
Create Date: 2026-10-02 18:10:56.484122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c326b0c451ac'
down_revision: Union[str, Sequence[str], None] = '0d0919441a3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('career_goals', sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('career_goals', 'is_primary')
    # ### end Alembic commands ###
