"""create career requirement tables

Revision ID: c9f62eae4df4
Revises: 14bd65acd0a3
Create Date: 2026-10-01 11:33:04.506508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9f62eae4df4'
down_revision: Union[str, Sequence[str], None] = '14bd65acd0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_skill_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('skill_type', sa.String(length=30), nullable=False),
    sa.Column('element_id', sa.String(length=30), nullable=False),
    sa.Column('element_name', sa.String(length=200), nullable=False),
    sa.Column('scale_id', sa.String(length=20), nullable=False),
    sa.Column('scale_name', sa.String(length=100), nullable=False),
    sa.Column('data_value', sa.Float(), nullable=False),
    sa.Column('not_relevant', sa.Boolean(), nullable=True),
    sa.Column('recommend_suppress', sa.Boolean(), nullable=True),
    sa.Column('source_date', sa.String(length=50), nullable=True),
    sa.Column('domain_source', sa.String(length=100), nullable=True),
    sa.Column('onet_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'skill_type', 'element_id', 'scale_id', name='uq_career_skill_requirement')
    )
    op.create_index(op.f('ix_career_skill_requirements_career_id'), 'career_skill_requirements', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_skill_requirements_element_id'), 'career_skill_requirements', ['element_id'], unique=False)
    op.create_index(op.f('ix_career_skill_requirements_element_name'), 'career_skill_requirements', ['element_name'], unique=False)
    op.create_index(op.f('ix_career_skill_requirements_skill_type'), 'career_skill_requirements', ['skill_type'], unique=False)
    op.create_table('career_software_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('career_id', sa.UUID(), nullable=False),
    sa.Column('element_id', sa.String(length=30), nullable=False),
    sa.Column('element_name', sa.String(length=200), nullable=False),
    sa.Column('workplace_example', sa.String(length=300), nullable=False),
    sa.Column('hot_technology', sa.Boolean(), nullable=False),
    sa.Column('in_demand', sa.Boolean(), nullable=False),
    sa.Column('onet_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'element_id', 'workplace_example', name='uq_career_software_requirement')
    )
    op.create_index(op.f('ix_career_software_requirements_career_id'), 'career_software_requirements', ['career_id'], unique=False)
    op.create_index(op.f('ix_career_software_requirements_element_id'), 'career_software_requirements', ['element_id'], unique=False)
    op.create_index(op.f('ix_career_software_requirements_element_name'), 'career_software_requirements', ['element_name'], unique=False)
    op.create_index(op.f('ix_career_software_requirements_workplace_example'), 'career_software_requirements', ['workplace_example'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_software_requirements_workplace_example'), table_name='career_software_requirements')
    op.drop_index(op.f('ix_career_software_requirements_element_name'), table_name='career_software_requirements')
    op.drop_index(op.f('ix_career_software_requirements_element_id'), table_name='career_software_requirements')
    op.drop_index(op.f('ix_career_software_requirements_career_id'), table_name='career_software_requirements')
    op.drop_table('career_software_requirements')
    op.drop_index(op.f('ix_career_skill_requirements_skill_type'), table_name='career_skill_requirements')
    op.drop_index(op.f('ix_career_skill_requirements_element_name'), table_name='career_skill_requirements')
    op.drop_index(op.f('ix_career_skill_requirements_element_id'), table_name='career_skill_requirements')
    op.drop_index(op.f('ix_career_skill_requirements_career_id'), table_name='career_skill_requirements')
    op.drop_table('career_skill_requirements')
    # ### end Alembic commands ###
