"""create skill evidence tables

Revision ID: de94f860d607
Revises: c1ad0f75e963
Create Date: 2026-09-29 11:25:30.150065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de94f860d607'
down_revision: Union[str, Sequence[str], None] = 'c1ad0f75e963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_canonical_name'), 'skills', ['canonical_name'], unique=True)
    op.create_index(op.f('ix_skills_category'), 'skills', ['category'], unique=False)
    op.create_table('student_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('claimed_proficiency', sa.Float(), nullable=True),
    sa.Column('estimated_proficiency', sa.Float(), nullable=True),
    sa.Column('evidence_confidence', sa.Float(), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_student_skill_user_skill')
    )
    op.create_index(op.f('ix_student_skills_skill_id'), 'student_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_student_skills_user_id'), 'student_skills', ['user_id'], unique=False)
    op.create_table('skill_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_skill_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('source_section', sa.String(length=100), nullable=True),
    sa.Column('evidence_text', sa.Text(), nullable=True),
    sa.Column('evidence_status', sa.String(length=30), nullable=False),
    sa.Column('evidence_strength', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_skill_id'], ['student_skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_skill_id', 'source_type', 'source_reference', 'source_section', name='uq_skill_evidence_source')
    )
    op.create_index(op.f('ix_skill_evidence_evidence_status'), 'skill_evidence', ['evidence_status'], unique=False)
    op.create_index(op.f('ix_skill_evidence_source_type'), 'skill_evidence', ['source_type'], unique=False)
    op.create_index(op.f('ix_skill_evidence_student_skill_id'), 'skill_evidence', ['student_skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_evidence_student_skill_id'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_source_type'), table_name='skill_evidence')
    op.drop_index(op.f('ix_skill_evidence_evidence_status'), table_name='skill_evidence')
    op.drop_table('skill_evidence')
    op.drop_index(op.f('ix_student_skills_user_id'), table_name='student_skills')
    op.drop_index(op.f('ix_student_skills_skill_id'), table_name='student_skills')
    op.drop_table('student_skills')
    op.drop_index(op.f('ix_skills_category'), table_name='skills')
    op.drop_index(op.f('ix_skills_canonical_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
